### ISSUE TITLE
Config loading more then one time

### ISSUE THREAD

**Issue by kolkov** [ochinchina/supervisord#231] opened 2020-10-17 22:31 UTC
Hi! Whats wrong?
![image](https://user-images.githubusercontent.com/3740898/96354633-6306ad00-10e1-11eb-837c-d6530ee96673.png)

**Comment by davixcky** [comment] 2020-10-20 00:47
I'm having the same issue. 
![image](https://user-images.githubusercontent.com/34346877/96526651-daece880-1243-11eb-97c5-1ba9df0b5eae.png)

**Comment by ochinchina** [comment] 2020-10-24 13:54
I will check this issue

**Comment by ochinchina** [comment] 2020-12-27 12:35
@kolkov could you please paste your supervisor configuration file here? and which supervisor version is used? have you checked if the latest supervisor has the same issue?

**Comment by kolkov** [comment] 2020-12-27 15:05
> @kolkov could you please paste your supervisor configuration file here? and which supervisor version is used? have you checked if the latest supervisor has the same issue?
Yes! Your `go.sum` file is still outdated.
https://github.com/ochinchina/supervisord/blob/2bf7dd167a1331bd3a2bd538145b236ffad3a85f/go.sum#L75

**Comment by babykart** [comment] 2021-01-08 12:54
Same _problem_ for me with v0.6.9 or master.

Build command:
```
go generate
GOOS=linux go build -tags release -o supervisord
```

Configuration file _supervisord.conf_:
```
; supervisord config file

[inet_http_server]
port=:9001

[supervisord]
pidfile=/run/supervisord.pid
loglevel=error
logfile=/dev/stderr

[supervisorctl]
serverurl=http://127.0.0.1:9001

[include]
files = /etc/supervisord.d/*.conf
```

```
supervisord -c /etc/supervisord.conf
time="2021-01-08T12:18:01Z" level=info msg="load configuration from file" file=/etc/supervisord.conf
time="2021-01-08T12:18:01Z" level=info msg="load configuration from file" file=/etc/supervisord.d/dev0.conf
time="2021-01-08T12:18:01Z" level=info msg="load configuration from file" file=/etc/supervisord.d/dev1.conf
time="2021-01-08T12:18:01Z" level=info msg="load configuration from file" file=/etc/supervisord.d/webhook.conf
```

Minimum output for all `supervisord ctl` commands:
```
INFO[2021-01-08T12:39:33Z] load configuration from file                  file=/etc/supervisord.conf
INFO[2021-01-08T12:39:33Z] load configuration from file                  file=/etc/supervisord.d/dev0.conf
INFO[2021-01-08T12:39:33Z] load configuration from file                  file=/etc/supervisord.d/dev1.conf
INFO[2021-01-08T12:39:33Z] load configuration from file                  file=/etc/supervisord.d/webhook.conf
INFO[2021-01-08T12:39:33Z] load configuration from file                  file=/etc/supervisord.conf
INFO[2021-01-08T12:39:33Z] load configuration from file                  file=/etc/supervisord.d/dev0.conf
INFO[2021-01-08T12:39:33Z] load configuration from file                  file=/etc/supervisord.d/dev1.conf
INFO[2021-01-08T12:39:33Z] load configuration from file                  file=/etc/supervisord.d/webhook.conf
INFO[2021-01-08T12:39:33Z] load configuration from file                  file=/etc/supervisord.conf
INFO[2021-01-08T12:39:33Z] load configuration from file                  file=/etc/supervisord.d/dev0.conf
INFO[2021-01-08T12:39:33Z] load configuration from file                  file=/etc/supervisord.d/dev1.conf
INFO[2021-01-08T12:39:33Z] load configuration from file                  file=/etc/supervisord.d/webhook.conf
<...>
```

**Comment by ochinchina** [comment] 2021-01-11 05:40
@kolkov fixed now, please try again, thanks!

**Comment by babykart** [comment] 2021-01-11 22:36
@ochinchina no more verbose output ! thx ! but now, it appears a regression on the command `supervisord ctl reload` where the supervisord crash with the following error:

```
panic: duplicate metrics collector registration attempted

goroutine 38 [running]:
github.com/prometheus/client_golang/prometheus.(*Registry).MustRegister(0xc00007c7d0, 0xc0003f34a0, 0x1, 0x1)
	/root/go/pkg/mod/github.com/prometheus/client_golang@v1.9.0/prometheus/registry.go:403 +0xad
github.com/prometheus/client_golang/prometheus.MustRegister(...)
	/root/go/pkg/mod/github.com/prometheus/client_golang@v1.9.0/prometheus/registry.go:178
main.(*XMLRPC).startHTTPServer(0xc000010380, 0x0, 0x0, 0x0, 0x0, 0xa49984, 0x3, 0xc00042b0b7, 0x5, 0xc0001baab0, ...)
	/usr/src/supervisord/xmlrpc.go:104 +0x102
main.(*XMLRPC).StartInetHTTPServer(0xc000010380, 0x0, 0x0, 0x0, 0x0, 0xc00042b0b7, 0x5, 0xc0001baab0, 0xc0003f3450)
	/usr/src/supervisord/xmlrpc.go:90 +0xa6
created by main.(*Supervisor).startHTTPServer
	/usr/src/supervisord/supervisor.go:518 +0x711
```

**Comment by ochinchina** [comment] 2021-01-12 09:16
this is caused by the prometheus integration, I will check it

**Comment by ochinchina** [comment] 2021-01-12 09:31
@babykart I fixed it, please try it

**Comment by babykart** [comment] 2021-01-12 10:07
@ochinchina problem fixed, thx.

**Closed** 2021-01-13 01:08 UTC
